spring:
  application:
    name: task-provider
db:
  host: localhost
  port: 54320
  database: task_manager
  username: postgres
  password: admin
kafka:
  properties:
    "[bootstrap.servers]": moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
    "[sasl.jaas.config]": org.apache.kafka.common.security.scram.ScramLoginModule required username="2z2j7jw9" password="gGBcXuQW6peGnHhInj9TE09n_d4IadbE";
    "[client.id]": 2z2j7jw9-producer
    "[acks]": all
    "[delivery.timeout.ms]": 90000
    "[enable.idempotence]": true
    "[batch.size]": 10240
    "[linger.ms]": 100
    "[security.protocol]": SASL_SSL
    "[sasl.mechanism]": SCRAM-SHA-256